name: CustomPlugin
version: ${project.version}
main: io.github.jennas_lee.customplugin.CustomPlugin
api-version: 1.17
commands:
  preventsweetberries:
    description: Prevent sweet berries in the server.
    usage: /preventsweetberries
    aliases: [enable, disable]